# Generated by Django 3.2 on 2021-07-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userFname', models.CharField(max_length=50)),
                ('userLname', models.CharField(max_length=50)),
                ('userAge', models.IntegerField()),
                ('userDob', models.DateField()),
                ('userEmail', models.EmailField(max_length=50)),
                ('userGender', models.CharField(max_length=10)),
                ('userSpecializedField', models.CharField(max_length=30)),
                ('userDesignation', models.CharField(max_length=30)),
                ('userQualification', models.CharField(max_length=30)),
                ('userWorkingPlace', models.CharField(max_length=30)),
                ('userWorkingHour1', models.TimeField()),
                ('userWorkingHour2', models.TimeField()),
                ('userConsultationFees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('userCnumber', models.CharField(max_length=30)),
            ],
        ),
    ]
