# Generated by Django 3.2 on 2021-08-03 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorList', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
